import contract_proposals.all_overtime_as_doubletime
import contract_proposals.hazard_tunnel_pay
import contract_proposals.walk_in_walk_out
import contract_proposals.shift_work
import contract_proposals.paid_sick_time
import contract_proposals.paid_holidays
import contract_proposals.optional_vacation_fund
import contract_proposals.manditory_app_rotation
import contract_proposals.increased_boot_stipend
import contract_proposals.twenty_over_three

contract_proposals.all_overtime_as_doubletime
contract_proposals.hazard_tunnel_pay
contract_proposals.walk_in_walk_out
contract_proposals.shift_work
contract_proposals.paid_sick_time
contract_proposals.paid_holidays
contract_proposals.optional_vacation_fund
contract_proposals.manditory_app_rotation
contract_proposals.increased_boot_stipend
contract_proposals.twenty_over_three

